In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
feat_save_dir = '/home/amanda/Documents/feat_folder/'
vc_impression_data = pd.read_pickle(feat_save_dir+'vc_prediction_df.pkl')

In [4]:
vc_impression_data = pd.read_pickle(feat_save_dir+'vc_prediction_df.pkl')

In [11]:
vc_impression_data.to_csv('tmp_data/vc_raw_prediction.csv')

In [12]:
test_df = pd.read_csv('tmp_data/vc_raw_prediction.csv')

In [10]:
vc_impression_data.head()

,trustworthy,intelligent,attractive,aggressive,responsible,sociable
vc5121_cb.jpeg,5.306906,5.179530,4.207136,3.368832,5.250375,5.365229
vc4009_cb.jpeg,4.990458,5.304036,3.822252,3.885132,5.243190,4.894275
vc4545_cb.jpeg,5.160250,4.837602,3.909858,3.431939,5.053713,5.195699
vc4001_cb.jpeg,5.046115,5.277191,5.066257,3.485938,5.085218,5.034356
vc4004_cb.jpeg,5.652349,5.296026,4.749463,2.767648,5.437033,6.228976

In [13]:
test_df.head()

,Unnamed: 0,trustworthy,intelligent,attractive,aggressive,responsible,sociable
0,vc5121_cb.jpeg,5.306906,5.179530,4.207136,3.368832,5.250375,5.365229
1,vc4009_cb.jpeg,4.990457,5.304036,3.822252,3.885132,5.243190,4.894275
2,vc4545_cb.jpeg,5.160250,4.837602,3.909858,3.431939,5.053713,5.195699
3,vc4001_cb.jpeg,5.046115,5.277191,5.066257,3.485938,5.085218,5.034356
4,vc4004_cb.jpeg,5.652349,5.296026,4.749463,2.767648,5.437033,6.228976

In [29]:
test_df['vc_id'] = pd.Series([s[:-8] for s in test_df['Unnamed: 0'].values], index=test_df.index)

In [23]:
vc_funding_data = pd.read_pickle('tmp_data/vc_df.pkl')

In [24]:
vc_funding_data.head()

,uuid,short_id,directory,tw_img_path,cb_img_path,VC - Investment # rank,VC - Investment $ rank
0,69e7be12-7b53-5a66-e93c-f691d97e48a7,vc1,vc0,vc0/vc1_tw.jpeg,vc0/vc1_cb.jpeg,0.193725,0.246069
1,4b7fc2e7-4ace-cecd-a937-fd1d572b1cd8,vc2,vc0,vc0/vc2_tw.jpeg,vc0/vc2_cb.jpeg,0.459014,0.233457
2,dc7c4f37-4cd7-0e26-c7d6-16ba8ac419d4,vc3,vc0,vc0/vc3_tw.jpeg,vc0/vc3_cb.jpeg,0.459014,0.233457
3,b7f7a76b-b715-bdd6-421a-d3a176254f9d,vc4,vc0,vc0/vc4_tw.jpeg,vc0/vc4_cb.jpeg,0.064119,0.073312
4,3606a0f9-bf2b-760a-2884-987898008183,vc5,vc0,vc0/vc5_tw.jpeg,vc0/vc5_cb.jpeg,0.064119,0.073312

In [30]:
short_vc_fund_df = vc_funding_data[vc_funding_data['short_id'].isin(test_df['vc_id'])]

In [31]:
short_vc_fund_df.head()

,uuid,short_id,directory,tw_img_path,cb_img_path,VC - Investment # rank,VC - Investment $ rank
0,69e7be12-7b53-5a66-e93c-f691d97e48a7,vc1,vc0,vc0/vc1_tw.jpeg,vc0/vc1_cb.jpeg,0.193725,0.246069
1,4b7fc2e7-4ace-cecd-a937-fd1d572b1cd8,vc2,vc0,vc0/vc2_tw.jpeg,vc0/vc2_cb.jpeg,0.459014,0.233457
2,dc7c4f37-4cd7-0e26-c7d6-16ba8ac419d4,vc3,vc0,vc0/vc3_tw.jpeg,vc0/vc3_cb.jpeg,0.459014,0.233457
3,b7f7a76b-b715-bdd6-421a-d3a176254f9d,vc4,vc0,vc0/vc4_tw.jpeg,vc0/vc4_cb.jpeg,0.064119,0.073312
4,3606a0f9-bf2b-760a-2884-987898008183,vc5,vc0,vc0/vc5_tw.jpeg,vc0/vc5_cb.jpeg,0.064119,0.073312

In [32]:
short_vc_fund_df = short_vc_fund_df.set_index('short_id')
short_vc_fund_df = short_vc_fund_df.reindex(index=test_df['vc_id'])
short_vc_fund_df = short_vc_fund_df.reset_index()

In [34]:
short_vc_fund_df.head()

,vc_id,uuid,directory,tw_img_path,cb_img_path,VC - Investment # rank,VC - Investment $ rank
0,vc5121,3cf70a10-6f97-c192-4847-d2461c2c61d4,vc5,vc5/vc5121_tw.jpeg,vc5/vc5121_cb.jpeg,0.767378,0.827471
1,vc4009,060ece34-94ff-b6fb-9a53-402a7dbcfa05,vc4,vc4/vc4009_tw.jpeg,vc4/vc4009_cb.jpeg,0.404391,0.370280
2,vc4545,4589663e-64fc-3f5e-ff48-83e168738d81,vc4,vc4/vc4545_tw.jpeg,vc4/vc4545_cb.jpeg,0.914685,0.887184
3,vc4001,6c682896-0640-6787-9529-1d6cbdf6045b,vc4,vc4/vc4001_tw.jpeg,vc4/vc4001_cb.jpeg,0.135683,0.133936
4,vc4004,2180929c-4be3-922f-be80-95895f620883,vc4,vc4/vc4004_tw.jpeg,vc4/vc4004_cb.jpeg,0.135683,0.236192

In [35]:
test_df.head()

,Unnamed: 0,trustworthy,intelligent,attractive,aggressive,responsible,sociable,vc_id
0,vc5121_cb.jpeg,5.306906,5.179530,4.207136,3.368832,5.250375,5.365229,vc5121
1,vc4009_cb.jpeg,4.990457,5.304036,3.822252,3.885132,5.243190,4.894275,vc4009
2,vc4545_cb.jpeg,5.160250,4.837602,3.909858,3.431939,5.053713,5.195699,vc4545
3,vc4001_cb.jpeg,5.046115,5.277191,5.066257,3.485938,5.085218,5.034356,vc4001
4,vc4004_cb.jpeg,5.652349,5.296026,4.749463,2.767648,5.437033,6.228976,vc4004

In [63]:
api_data = pd.read_csv('/home/amanda/Github/impression_personality/vc-labels.txt', sep="\t", header=None)
api_data.columns = ["faceId", "faceTopDimension", "faceLeftDimension", "faceWidthDimension", "faceHeightDimension",
                    "smile", "pitch", "roll", "yaw", "gender", "age", "moustache", "beard", "sideburns", "glasses",
                    "anger", "contempt", "disgust", "fear", "happiness", "neutral", "sadness", "surprise",
                    "blurlevel",
                    "blurvalue", "exposurelevel", "exposurevalue", "noiselevel", "noisevalue", "eymakeup",
                    "lipmakeup",
                    "foreheadoccluded", "eyeoccluded", "mouthoccluded", "hair-bald", "hair-invisible", "img_name"]
api_data = api_data.drop(api_data.index[0])
api_data = api_data[['img_name', 'gender', 'age']]
print(len(api_data))
api_data = api_data.drop_duplicates()  # there are some repetitive images.
print(len(api_data))

10855
10843

In [64]:
api_data

              img_name  gender   age
1        vc941_cb.jpeg    male  45.3
2        vc829_cb.jpeg    male  29.5
3        vc813_tw.jpeg    male  52.3
4         vc23_cb.jpeg    male  50.1
5        vc483_cb.jpeg  female  37.4
6        vc307_cb.jpeg    male  36.9
7        vc123_tw.jpeg    male  33.6
8        vc317_cb.jpeg    male  53.3
9        vc552_cb.jpeg  female  48.7
10       vc776_tw.jpeg    male    42
11       vc542_cb.jpeg  female  30.8
12       vc578_tw.jpeg    male  49.7
13       vc624_cb.jpeg    male    31
14       vc119_cb.jpeg    male  46.3
15       vc880_cb.jpeg  female  48.5
16       vc237_tw.jpeg    male  40.1
17       vc656_cb.jpeg    male  35.2
18       vc646_cb.jpeg    male  32.1
19       vc530_cb.jpeg    male    40
20         vc2_cb.jpeg    male  44.2
21       vc589_cb.jpeg    male  30.8
22       vc599_cb.jpeg    male  31.4
23        vc41_cb.jpeg  female  27.5
24       vc871_tw.jpeg    male  52.3
25        vc51_cb.jpeg    male  39.7
26       vc933_cb.jpeg  female  33.9
27       vc763_cb.jpeg    male  46.1
28       vc126_cb.jpeg    male  44.3
29       vc136_cb.jpeg    male  42.3
30       vc338_cb.jpeg    male  33.6
...                ...     ...   ...
10826  vc12755_cb.jpeg    male  64.7
10827  vc12419_tw.jpeg    male  23.9
10828  vc12745_cb.jpeg    male  45.7
10829  vc12915_cb.jpeg    male  26.1
10830  vc12282_cb.jpeg    male    31
10831  vc12292_cb.jpeg    male  38.6
10832  vc12343_cb.jpeg    male  39.6
10833  vc12353_cb.jpeg    male    55
10834  vc12516_cb.jpeg    male  29.2
10835  vc12506_cb.jpeg    male  52.6
10836  vc12708_cb.jpeg    male  29.3
10837  vc12660_cb.jpeg    male  29.2
10838  vc12025_cb.jpeg    male  39.4
10839  vc12035_cb.jpeg    male    27
10840  vc12201_tw.jpeg    male  70.9
10841  vc12047_cb.jpeg    male  32.5
10842  vc12057_cb.jpeg    male  40.1
10843  vc12612_cb.jpeg    male  45.9
10844  vc12426_tw.jpeg    male  47.6
10845  vc12602_cb.jpeg    male  46.8
10846  vc12574_cb.jpeg    male  33.1
10847  vc12564_cb.jpeg  female  28.8
10848  vc12259_cb.jpeg    male    31
10849  vc12331_cb.jpeg  female    23
10850  vc12249_cb.jpeg    male  27.9
10851  vc12681_tw.jpeg    male    36
10852  vc12398_cb.jpeg    male  60.3
10853  vc12967_cb.jpeg    male  35.1
10854  vc12977_cb.jpeg    male  33.2
10855  vc12196_cb.jpeg    male  50.3

[10843 rows x 3 columns]